form:
  date_allattributes:
    type: date
    label: date label
    tooltip: 'A useful hint for this date field.'
    column: is-two-thirds
    placeholder: placeholder value for input
    readonly: true
    validation:
      required: false
  date_writeable:
    type: date
    label: writeable date
    validation:
      start: '2023-01-01'
      end: '2025-12-31'
