meta:
  email:
    subject: 'Numberinput Email'
    recipients:
      - recipient1@example.com
form:
  num_allattributes:
    type: numberinput
    label: number label
    tooltip: 'A useful hint for this number field.'
    column: is-half
    placeholder: enter a number
    readonly: true
    validation:
      required: false
  num_with_suffix:
    type: numberinput
    label: Size
    suffix: mm
    column: is-half
    placeholder: enter size in millimeters
    validation:
      required: true
      min: 0
