form:
  datetime_allattributes:
    type: datetime
    label: datetime label
    tooltip: 'A useful hint for this datetime field.'
    column: is-two-thirds
    placeholder: placeholder value for input
    readonly: true
    validation:
      required: false
  datetime_writeable:
    type: datetime
    label: writeable datetime
    validation:
      start: '2025-01-01 12:00'
      end: '2025-12-31 12:00'
