meta:
  title: "Task Priority Sorter"
  email:
    subject: 'Email subject'
    recipients:
      - recipient1@example.com
      - recipient2@example.com
form:
  description:
    type: markdown
    markdown: "Drag and drop to reorder tasks by priority"
  task_priorities:
    type: sorter
    label: "Task Priorities"
    tooltip: "Drag items to reorder them by priority (highest to lowest)"
    alignment: horizontal
    items:
      - "Critical Bug Fixes"
      - "Feature Development"
      - "Code Review"
      - "Documentation"
      - "Testing"
      - "Code Refactoring"
    validation:
      required: true

  project_phases:
    type: sorter
    label: "Project Phases"
    tooltip: "Order the phases as they should be executed"
    items:
      - "Planning & Requirements"
      - "Design & Architecture"
      - "Development"
      - "Quality Assurance"
      - "Deployment"
      - "Maintenance"
    column: "is-half"

  team_preferences:
    type: sorter
    label: "Team Meeting Preferences"
    tooltip: "Rank meeting types by team preference"
    items:
      - "Daily Standup"
      - "Sprint Retrospective"
      - "Sprint Planning"
      - "Sprint Review"
      - "One-on-One"
    column: "is-half"
    validation:
      required: false
