form:
  time_allattributes:
    type: time
    label: time label
    tooltip: 'A useful hint for this time field.'
    column: is-two-thirds
    placeholder: placeholder value for input
    readonly: true
    validation:
      required: false
  time_writeable:
    type: time
    label: writeable time
    validation:
      start: '09:00'
      end: '17:00'
