form:
  time_allattributes:
    type: time
    label: time label
    tooltip: 'A useful hint for this time field.'
    column: is-two-thirds
    placeholder: placeholder value for input
    readonly: true
    validation:
      required: false
