name: Test and Create Release

on:
  push:
  workflow_dispatch:

env:
  DATA_DIR: 'cypress/yaml'
  CYPRESS_BASE_URL: "http://localhost:8181"

jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Composer
        uses: php-actions/composer@v6
      - name: npm build
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm ci
      - run: npm run build --if-present
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: composer run start
  release:
    needs: cypress-test
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Composer
        uses: php-actions/composer@v6
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm ci --omit-dev
      - run: npm run build
      - name: build
        run: |
          ./build.sh
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
